Repository kayoumido/HEIGVD-PRO-A-11, pull requests merged in 2020-05, with the labels that each got.

#127 V1/116 stylize authentication
  src/resources/js/api/index.js
  src/resources/js/components/Authentication.vue
  src/resources/js/router.js
Labels: critical, frontend

#129 V1/40 create presentation
  src/package-lock.json
  src/package.json
  src/resources/js/app.js
  src/resources/js/components/CreatePresentation.vue
  src/resources/js/router.js
Labels: critical, frontend

#139 V1/53 54 subscribe unsubscribe frontend
  src/resources/js/bootstrap.js
  src/resources/js/components/Presentation.vue
Labels: frontend

#137 #131 Change sidebar logic
  src/resources/js/components/layout/SideBar.vue
  src/resources/js/router.js
Labels: frontend

#142 V1/32 account creation
  src/resources/js/components/AccountCreation.vue
  src/resources/js/router.js
Labels: frontend

#133 V1/35 password recovery
  src/resources/js/components/Reset.vue
  src/resources/js/components/ResetPassword.vue
  src/resources/js/router.js
Labels: frontend

#147 V1/144 unify frontend code
  src/app/Providers/AppServiceProvider.php
  src/public/docs/collection.json
  src/public/docs/index.html
  src/resources/docs/source/.compare.md
  src/resources/docs/source/index.md
  src/resources/js/app.js
  src/resources/js/bootstrap.js
  src/resources/js/components/AccountCreation.vue
  src/resources/js/components/AccountEdit.vue
  src/resources/js/components/Authentication.vue
  src/resources/js/components/CreatePresentation.vue
  src/resources/js/components/Hello.vue
  src/resources/js/components/ListPresentations.vue
  src/resources/js/components/Presentation.vue
  src/resources/js/components/Reset.vue
  src/resources/js/components/ResetPassword.vue
  src/resources/js/components/layout/AlertMessage.vue
  src/resources/js/components/layout/App.vue
  src/resources/js/components/layout/SideBar.vue
  src/resources/js/router.js
  src/storage/responses/choice.get.json
  src/storage/responses/choices.get.json
  src/storage/responses/poll.get.json
  src/storage/responses/poll.results.json
  src/storage/responses/polls.get.json
  src/storage/responses/presentation.get.json
  src/storage/responses/presentations.get.json
  src/storage/responses/user.get.json
Labels: backend, critical, frontend

#146 V1/50 search presentation
  .gitignore
  README.md
  src/.env.example
  src/app/Http/Controllers/API/PresentationController.php
  src/app/Presentation.php
  src/composer.json
  src/composer.lock
  src/config/app.php
  src/config/scout.php
  src/routes/api.php
Labels: backend

#141 V1/140 get role on api
  src/app/Http/Resources/PresentationResource.php
  src/public/docs/collection.json
  src/public/docs/index.html
  src/resources/docs/source/.compare.md
  src/resources/docs/source/index.md
Labels: backend

#124 V1/44 password recovery
  README.md
  src/.env.example
  src/app/Http/Controllers/API/AuthController.php
  src/app/Mail/ResetPasswordMail.php
  src/public/docs/collection.json
  src/public/docs/index.html
  src/resources/docs/source/.compare.md
  src/resources/docs/source/index.md
  src/resources/views/Email/passwordReset.blade.php
  src/routes/api.php
Labels: backend

#138 V1/111 V1/69 Polls view & create
  src/app/Choice.php
  src/app/Http/Controllers/API/ChoiceController.php
  src/app/Http/Controllers/API/PollController.php
  src/app/Http/Kernel.php
  src/app/Http/Middleware/CheckPollRoles.php
  src/app/Poll.php
  src/app/Poll/PollStatuses.php
  src/app/Presentation.php
  src/routes/api.php
Labels: backend, previous sprint

#161 V1/48 delete presentation
  src/resources/js/components/ListPresentations.vue
  src/resources/js/components/Presentation.vue
Labels: frontend

#152 V1/37 search presentation
  src/resources/js/components/Presentation.vue
  src/resources/js/components/layout/SearchBar.vue
Labels: frontend

#168 #157 Implement choice update
  src/app/Http/Controllers/API/ChoiceController.php
  src/routes/api.php
Labels: backend

#165 V1/72 deletepaul
  src/app/Http/Controllers/API/PollController.php
  src/app/Poll/PollStatus.php
  src/app/Presentation.php
Labels: backend, priority 1

#172 V1/75 answer poll
  src/app/Http/Controllers/API/PollController.php
  src/app/Http/Kernel.php
  src/app/Http/Middleware/CheckChoiceBelongsToPoll.php
  src/app/Http/Middleware/CheckPollIsVotable.php
  src/app/Http/Middleware/CheckSameUserAsRequest.php
  src/app/Http/Requests/VoteRequest.php
  src/app/Rules/UserVoted.php
  src/routes/api.php
Labels: backend

#163 V1/134 user session management
  src/resources/js/components/AccountCreation.vue
  src/resources/js/components/Authentication.vue
  src/resources/js/components/layout/App.vue
  src/resources/js/components/layout/SideBar.vue
  src/resources/js/components/layout/UserTooltip.vue
  src/resources/js/router.js
Labels: frontend

#171 V1/manage poll choices
  src/app/Http/Controllers/API/PollController.php
  src/app/Http/Resources/PollResource.php
  src/resources/js/components/AccountCreation.vue
  src/resources/js/components/AccountEdit.vue
  src/resources/js/components/Authentication.vue
  src/resources/js/components/Choice.vue
  src/resources/js/components/Choices.vue
  src/resources/js/components/CreateChoice.vue
  src/resources/js/components/CreatePoll.vue
  src/resources/js/components/CreatePresentation.vue
  src/resources/js/components/EditPresentation.vue
  src/resources/js/components/ListPresentations.vue
  src/resources/js/components/Poll.vue
  src/resources/js/components/PollResult.vue
  src/resources/js/components/Polls.vue
  src/resources/js/components/Presentation.vue
  src/resources/js/components/Reset.vue
  src/resources/js/components/ResetPassword.vue
  src/resources/js/components/layout/App.vue
  src/resources/js/router.js
  src/storage/responses/poll.get.json
  src/storage/responses/poll.results.json
  src/storage/responses/polls.get.json
Labels: frontend

#178 V1/174 175 code refactor and new design
  src/package-lock.json
  src/package.json
  src/resources/js/app.js
  src/resources/js/bootstrap.js
  src/resources/js/components/AccountCreation.vue
  src/resources/js/components/AccountEdit.vue
  src/resources/js/components/Authentication.vue
  src/resources/js/components/Choice.vue
  src/resources/js/components/CreateChoice.vue
  src/resources/js/components/CreatePoll.vue
  src/resources/js/components/CreatePresentation.vue
  src/resources/js/components/EditPresentation.vue
  src/resources/js/components/EditableText.vue
  src/resources/js/components/ListPresentations.vue
  src/resources/js/components/Poll.vue
  src/resources/js/components/Polls.vue
  src/resources/js/components/Presentation.vue
  src/resources/js/components/Reset.vue
  src/resources/js/components/ResetPassword.vue
  src/resources/js/components/layout/AlertMessage.vue
  src/resources/js/components/layout/App.vue
  src/resources/js/components/layout/AppTitle.vue
  src/resources/js/components/layout/CustomFont.vue
  src/resources/js/components/layout/SearchBar.vue
  src/resources/js/components/layout/SideBar.vue
  src/resources/js/components/layout/UserTooltip.vue
  src/resources/js/router.js
  src/resources/js/store/auth.js
  src/resources/js/store/index.js
  src/resources/js/vuetify/index.js
  src/resources/views/Email/passwordReset.blade.php
  src/resources/views/app.blade.php
  src/routes/api.php
Labels: backend, frontend
